# -*- coding: utf-8 -*-
"""API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TxWDLZU5b3HL1VcSHtkMBM_lzVv_8gSm
"""

# =========================
# SECCION 1 - INSTALACIÓN DE DEPENDENCIAS
# =========================

# Se descomenta la primera vez que se corre en Google Colab para instalar todas las librerías requeridas para el sistema
#!pip install numpy scipy matplotlib scikit-learn mesa==3.0 -q

# =========================
# SECCION 2 - IMPORTS E INPUTS
# =========================

from mesa import Agent, Model
from mesa.space import SingleGrid # Espacio discreto donde se moveran los agentes
from mesa.space import MultiGrid
from mesa.time import RandomActivation # Para incluir Scheduler, qiue ayudará para ejecutar los agentes en orden aleatorio
from mesa.datacollection import DataCollector ## Para recolectar datos de la simulación
from matplotlib.collections import LineCollection
from mesa.space import SingleGrid

# Configuración de matplotlib para gráficas y animaciones
# %matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.animation as animation
plt.rcParams["animation.html"] = "jshtml"  # Para renderizar la animación directamente en Jupyter
matplotlib.rcParams['animation.embed_limit'] = 2**128 # Evita límite en animaciones grandes

# Librerías adicionales
import numpy as np
import pandas as pd
import time
import datetime

from collections import deque
import random


# Constantes para representar el estado de las celdas
EMPTY = 0 # Celda vacía
SMOKE = 1 # Celda con humo
FIRE = 2 # Celda con fuego
WALL = 3 # Celda con pared
DOOR_CLOSED = 4
DOOR_OPEN = 5
POI = 6 # Punto de interés (víctima/falsa alarma)

# =========================
# SECCIÓN 3 — AGENTE ASTRONAUTA
# =========================

from collections import deque
import random
from mesa import Agent

class Astronaut(Agent):
    """
    IA mejorada con aristas (paredes/puertas entre celdas):
      - BFS para acercarse a objetivo (permite puertas cerradas en planificación).
      - Abre puertas cerradas (1 AP) antes de entrar; con 1 AP puede abrir y esperar.
      - Prioriza: POI vivo -> POI muerto -> POI none -> fuego -> humo (selección de objetivo en parte 2).
      - Seguridad adyacente (apagar/limpiar) antes de avanzar (en parte 2).
      - Evita colisiones (no entra a celdas ocupadas).
      - Métricas para DataCollector (contadores en parte 2).

    Requiere en el modelo:
      - grid (SingleGrid recomendado) / is_cell_empty disponible
      - neighbors4(pos)
      - edge_is_wall_solid(a,b), edge_is_door_closed(a,b), _edge(a,b)
      - nursing_pos, airlock_pos
      - fire_positions, smoke_positions, poi_positions, victim_status
      - (opcional) model.random para reproducibilidad
    """
    VALID_STRATEGIES = {"reasoned", "random"}

    def __init__(self, unique_id, model, strategy=None):
        super().__init__(model)
        # AP y estado
        self.max_ap = getattr(model, "max_ap", 4)
        self.ap = self.max_ap
        self.carrying = False
        self.carrying_status = None  # 'alive' | 'dead'
        # Métricas (se usan en DataCollector)
        self.victims_saved = 0
        self.fires_extinguished = 0
        self.smoke_cleared = 0
        self.pois_found = 0
        # Log
        self.log = []  # Para registrar acciones por turno
        # Objetivo “pegajoso” (se usa en parte 2 del step)
        self.current_target = None


        # === Estrategia ===
        self.strategy = strategy or getattr(model, "default_strategy", "reasoned")
        if self.strategy not in self.VALID_STRATEGIES:
            self.strategy = "reasoned"

    def set_strategy(self, strategy: str):
        """Cambia la estrategia del agente en tiempo de ejecución."""
        if strategy not in self.VALID_STRATEGIES:
            raise ValueError(f"Estrategia inválida: {strategy}. Usa {self.VALID_STRATEGIES}.")
        self.strategy = strategy



    # ----------------- Helpers de vecindad y aristas -----------------
    def _adjacent4(self, pos):
        # Lo mantenemos por compatibilidad, aunque preferimos model.neighbors4
        x, y = pos
        return [(x+1,y), (x-1,y), (x,y+1), (x,y-1)]

    def _edge_is_wall(self, a, b):
        return self.model.edge_is_wall_solid(a, b)

    def _edge_is_door_closed(self, a, b):
        return self.model.edge_is_door_closed(a, b)

    def _cell_free(self, pos):
        """True si la celda está libre (evita colisiones)."""
        try:
            return self.model.grid.is_cell_empty(pos)
        except AttributeError:
            # Si fuera MultiGrid, evitamos entrar si hay otro Astronaut
            occupants = self.model.grid.get_cell_list_contents([pos])
            return all((o is self) or (not isinstance(o, Astronaut)) for o in occupants)

    # ----------------- Acciones sobre puertas -----------------
    def open_door_between(self, a, b):
        """Abre la puerta en la arista a<->b (si está cerrada) gastando 1 AP."""
        if self.ap >= 1 and self._edge_is_door_closed(a, b):
            e = self.model._edge(a, b)
            self.model.door_state_edge[e] = "open"
            self.ap -= 1
            self.log.append(f"Abre puerta entre {a} y {b}. AP={self.ap}")
            return True
        return False

    # ----------------- Movimiento -----------------
    def _try_move(self, new_pos):
        """
        Intenta mover al agente a new_pos:
          - No entra a fuego.
          - No atraviesa pared sólida.
          - Si hay puerta cerrada en la arista, puede: abrir+entrar (AP >= 1 + move_cost)
            o abrir solo si tiene 1 AP (prepara el siguiente turno).
          - Evita colisiones: no entra a celdas ocupadas.
        """
        if self.ap <= 0 or new_pos == self.pos:
            return False

        cur = self.pos

        # No pisar fuego
        if new_pos in self.model.fire_positions:
            return False

        # Pared sólida en la arista
        if self._edge_is_wall(cur, new_pos):
            return False

        move_cost = 1 + (1 if self.carrying else 0)
        rng = getattr(self.model, "random", None)

        # Puerta cerrada en la arista
        if self._edge_is_door_closed(cur, new_pos):
            total = 1 + move_cost  # abrir (1) + mover (move_cost)

            if self.ap >= total:
                # Solo abrimos si podemos entrar y la celda está libre (evita gastar AP inútil)
                if not self._cell_free(new_pos):
                    return False
                self.open_door_between(cur, new_pos)   # -1 AP
                # Re-check por seguridad (no debería cambiar entre líneas, pero es barato)
                if not self._cell_free(new_pos):
                    return False
                self.ap -= move_cost
                self.model.grid.move_agent(self, new_pos)
                return True

            elif self.ap == 1:
                # Abrir y preparar avance para el siguiente turno (aunque la celda esté ocupada)
                return self.open_door_between(cur, new_pos)

            return False

        if not self._cell_free(new_pos):
            return False

        # Movimiento normal (sin puerta)
        if self.ap >= move_cost and self._cell_free(new_pos):
            self.ap -= move_cost
            self.model.grid.move_agent(self, new_pos)
            return True

        return False

    # ----------------- Planificación -----------------
    def _astar_next_step(self, start, goal):
        """A* sobre celdas con aristas: pared sólida bloquea; puerta cerrada se permite (se abrirá al entrar)."""
        if start == goal:
            return None
        W, H = self.model.grid.width, self.model.grid.height

        def h(p):  # heurística Manhattan
            return abs(p[0]-goal[0]) + abs(p[1]-goal[1])

        open_set = {start}
        came_from = {}
        g = {start: 0}
        f = {start: h(start)}

        import heapq
        heap = [(f[start], start)]

        while heap:
            _, current = heapq.heappop(heap)
            if current == goal:
                # reconstruir el primer paso
                step = current
                while came_from.get(step, start) != start:
                    step = came_from[step]
                return step

            open_set.discard(current)

            for nb in self.model.neighbors4(current):
                # pared sólida NO se puede planear
                if not self.model.planning_passable(current, nb):
                    continue

                tentative_g = g[current] + 1  # costo uniforme
                if tentative_g < g.get(nb, 1e9):
                    came_from[nb] = current
                    g[nb] = tentative_g
                    fnb = tentative_g + h(nb)
                    f[nb] = fnb
                    if nb not in open_set:
                        open_set.add(nb)
                        heapq.heappush(heap, (fnb, nb))
        return None


    def _bfs_next_step(self, start, goal):
        """
        BFS sobre celdas, considerando aristas:
          - Pared sólida bloquea planificación.
          - Puerta cerrada se permite (se abrirá al intentar entrar).
        Devuelve el PRIMER paso desde 'start' hacia 'goal', o None si no hay ruta.
        """
        if start == goal:
            return None

        W, H = self.model.grid.width, self.model.grid.height
        q = deque([start])
        visited = {start}
        parent = {start: None}

        while q:
            cur = q.popleft()
            for nb in self.model.neighbors4(cur):
                if nb in visited:
                    continue
                # En planificación: pared sólida bloquea; puerta cerrada se permite
                if not self.model.planning_passable(cur, nb):
                    continue
                visited.add(nb)
                parent[nb] = cur
                if nb == goal:
                    # reconstruir primer paso
                    step = nb
                    while parent[step] != start:
                        step = parent[step]
                    return step
                q.append(nb)
        return None


    # ----------------- Movimiento aleatorio dirigido (opcional) -----------------
    def _random_move(self, prefer_towards=None):
        """
        Intenta moverse a un vecino válido:
          - Solo a vecinos atravesables (sin pared ni puerta cerrada), sin fuego y libres.
          - Si 'prefer_towards' se da, prefiere el vecino que reduce la distancia Manhattan al objetivo.
        """
        rng = getattr(self.model, "random", None)
        neighbors = list(self.model.neighbors4(self.pos))

        # Filtra solo vecinos válidos
        valid = []
        for nb in neighbors:
            if nb in self.model.fire_positions:
                continue
            if self._edge_is_wall(self.pos, nb):
                continue
            if self._edge_is_door_closed(self.pos, nb):
                # _random_move no abre puertas; solo camina si ya está libre
                continue
            if not self._cell_free(nb):
                continue
            valid.append(nb)

        if not valid:
            return False

        # Ordena por distancia al objetivo si se proporciona
        if prefer_towards is not None:
            valid.sort(key=lambda p: abs(p[0]-prefer_towards[0]) + abs(p[1]-prefer_towards[1]))

        # Intenta en ese orden (determinista si usas self.model.random y no re-ordenas)
        for nb in valid:
            if self._try_move(nb):
                return True

        # Si no hay vecinos válidos, intenta limpiar o apagar en su celda
        if self.pos in self.model.smoke_positions and self.ap >= 1:
            self.clear_smoke(self.pos)
            self.log.append(f"Limpia humo en su celda {self.pos}. AP={self.ap}")
            return True
        if self.pos in self.model.fire_positions and self.ap >= 2:
            self.extinguish_fire(self.pos)
            self.log.append(f"Apaga fuego en su celda {self.pos}. AP={self.ap}")
            return True

        return False

    def _do_safety_adjacent(self):
        """Acciones solo si la arista hacia el vecino es transitable: fuego > humo."""
        for nb in self.model.neighbors4(self.pos):
            if self.model.can_traverse(self.pos, nb) and nb in self.model.fire_positions and self.ap >= 2:
                self.extinguish_fire(nb)
                self.log.append(f"Apaga fuego adyacente en {nb}. AP={self.ap}")
                return True
        for nb in self.model.neighbors4(self.pos):
            if self.model.can_traverse(self.pos, nb) and nb in self.model.smoke_positions and self.ap >= 1:
                self.clear_smoke(nb)
                self.log.append(f"Limpia humo adyacente en {nb}. AP={self.ap}")
                return True
        return False

    def _neighbors_von_neumann(self, pos):
        # (No usada; preferimos model.neighbors4, se deja por compatibilidad)
        x, y = pos
        candidates = [(x+1,y), (x-1,y), (x,y+1), (x,y-1)]
        valid = []
        for nx, ny in candidates:
            if 0 <= nx < self.model.grid.width and 0 <= ny < self.model.grid.height:
                valid.append((nx, ny))
        return valid

    def _nearest(self, positions):
        if not positions:
            return None
        x0, y0 = self.pos
        return min(positions, key=lambda p: abs(p[0]-x0)+abs(p[1]-y0))

    def _select_target(self):
        """Prioridad: POI vivo -> POI muerto -> POI none -> fuego -> humo."""
        alive_pois = [p for p in self.model.poi_positions if self.model.victim_status.get(p) == 'alive']
        dead_pois  = [p for p in self.model.poi_positions if self.model.victim_status.get(p) == 'dead']
        any_pois   = [p for p in self.model.poi_positions if self.model.victim_status.get(p) == 'none']
        for bucket in (alive_pois, dead_pois, any_pois, self.model.fire_positions, self.model.smoke_positions):
            if bucket:
                return self._nearest(bucket)
        return None

    def _target_still_valid(self, t):
        """Verifica si el objetivo sigue existiendo en el mundo."""
        if t is None:
            return False
        # Si lleva víctima, el objetivo es fijo y lo maneja _choose_or_keep_target
        # Para el resto: sigue válido si está en alguna de estas colecciones actuales
        if t in self.model.poi_positions:
            return True
        if t in self.model.fire_positions:
            return True
        if t in self.model.smoke_positions:
            return True
        return False

    def _choose_or_keep_target(self):
        """Objetivo 'pegajoso': conserva el target si sigue válido; si no, selecciona uno nuevo."""
        if self.carrying:
            return self.model.nursing_pos if self.carrying_status == 'alive' else self.model.airlock_pos
        if self._target_still_valid(self.current_target):
            return self.current_target
        # Elegir uno nuevo
        self.current_target = self._select_target()
        return self.current_target

    def extinguish_fire(self, pos):
        if self.ap >= 2 and pos in self.model.fire_positions:
            try:
                self.model.fire_positions.remove(pos)
            except ValueError:
                # Ya fue removido por otro efecto concurrente
                return False
            self.fires_extinguished += 1
            self.ap -= 2
            return True
        return False

    def clear_smoke(self, pos):
        if self.ap >= 1 and pos in self.model.smoke_positions:
            try:
                self.model.smoke_positions.remove(pos)
            except ValueError:
                return False
            self.smoke_cleared += 1
            self.ap -= 1
            return True
        return False

    def _interact_here(self):
        """Levanta POI si está en la celda. Las falsas alarmas ('none') se descartan."""
        if self.pos in self.model.poi_positions:
            status = self.model.victim_status.get(self.pos, 'none')
            self.pois_found += 1
            # Remueve el POI del tablero
            try:
                self.model.poi_positions.remove(self.pos)
            except ValueError:
                pass
            self.model.victim_status.pop(self.pos, None)
            # Si es víctima (viva o muerta) y no trae carga, cargarla
            if status in ('alive', 'dead') and not self.carrying:
                self.carrying = True
                self.carrying_status = status
                self.log.append(f"Recoge víctima {status} en {self.pos}.")

    def _advance_towards(self, target_pos):
        """Da un paso (A* con fallback a BFS) hacia target_pos; con fallbacks de puerta/side-step."""
        if self.ap <= 0:
            return False

        # A* primero
        step = self._astar_next_step(self.pos, target_pos)
        if step is None:
            step = self._bfs_next_step(self.pos, target_pos)

        if step is None:
            return False

        # Intentar mover al 'step'
        old = self.pos
        # Si hay puerta cerrada justo hacia ese paso, intenta abrir+entrar si alcanza AP; si no, abre solo
        if self._edge_is_door_closed(self.pos, step):
            # _try_move intentará abrir+entrar si hay AP suficiente; si no, con AP==1 abrirá y regresará True
            moved = self._try_move(step)
            if moved:
                self.log.append(f"Avanza hacia {target_pos}: {old} -> {self.pos}. AP={self.ap}")
                return True
            # Si no pudo, al menos intenta abrir solo (si no se abrió ya)
            if self._open_adjacent_door_towards(target_pos):
                return True
            # Si tampoco, intenta side-step
            return self._sidestep_towards(target_pos)

        # Sin puerta de por medio: movimiento normal
        moved = self._try_move(step)
        if moved:
            self.log.append(f"Avanza hacia {target_pos}: {old} -> {self.pos}. AP={self.ap}")
            return True

        # Si no entró (ocupado o sin AP), prueba side-step
        if self._sidestep_towards(target_pos):
            return True

        # Nada
        return False

    # ----------------- Lógica por turno -----------------
    def step_reasoned(self):
        # Inicio de turno
        self.ap = self.max_ap
        self.log = [f"Astronauta {self.unique_id} inicia turno en {self.pos} con {self.ap} AP."]
        self._interact_here()

        guard = 50  # Evita loops raros en un mismo turno
        while self.ap > 0 and guard > 0:
            guard -= 1

            # Si trae víctima: prioridad absoluta = entregar
            if self.carrying:
                target = self.model.nursing_pos if self.carrying_status == 'alive' else self.model.airlock_pos

                # Seguridad adyacente primero
                if self._do_safety_adjacent():
                    continue

                # ¿Ya está en el punto de entrega?
                if self.pos == target:
                    if self.carrying_status == 'alive':
                        self.victims_saved += 1
                        self.log.append(f"Entrega víctima viva en {target}.")
                    else:
                        self.log.append(f"Entrega víctima muerta en {target}.")
                    self.carrying = False
                    self.carrying_status = None
                    self.current_target = None  # Reinicia objetivo
                    continue

                # Avanzar hacia el punto de entrega
                if self._advance_towards(target):
                    self._interact_here()  # Por si pisa un POI
                    continue

                # Sin ruta: intenta moverse acercándose o termina turno
                if self._random_move(prefer_towards=target):
                    self._interact_here()
                    continue

                # Nada que hacer: termina turno
                self.log.append("Atorado cargando: sin movimientos posibles. Termina turno.")
                self.ap = 0
                break
            # --- Si NO trae víctima ---
            # Seguridad adyacente primero
            if self._do_safety_adjacent():
                continue

            # ¿Hay algo aquí para interactuar? (p. ej., recoger POI)
            prev_carry = self.carrying
            self._interact_here()
            if self.carrying and not prev_carry:
                # Tras recoger, ahora su objetivo es punto de entrega
                continue

            # Elegir o mantener objetivo
            target = self._choose_or_keep_target()

            if target is None:
                # Nada que perseguir: moverse un paso válido (dirigido si hay rastro de target previo)
                if self._random_move():
                    self._interact_here()
                    continue
                else:
                    self.log.append("Sin objetivo y sin movimientos posibles. Termina turno.")
                    self.ap = 0
                    break

            # Avanzar hacia el objetivo elegido
            if self._advance_towards(target):
                self._interact_here()
                continue

            # Si no pudo avanzar (p. ej., puerta cerrada que abrió pero no alcanza a entrar, o bloqueo):
            # -> intenta moverse acercándose (sin abrir puertas aquí)
            if self._random_move(prefer_towards=target):
                self._interact_here()
                continue

            # (Opcional) Intentar brecha de pared si el modelo la soporta
            if hasattr(self.model, "damage_wall_edge"):
                # Heurística simple: intenta brechar hacia el vecino que acerque al objetivo (cuesta 2 AP)
                if self.ap >= 2:
                    best = None
                    best_score = 10**9
                    for nb in self.model.neighbors4(self.pos):
                        e = self.model._edge(self.pos, nb)
                        if e in self.model.wall_damage_edge and self.model.wall_damage_edge[e] < 2:
                            score = abs(nb[0]-target[0]) + abs(nb[1]-target[1])
                            if score < best_score:
                                best = nb; best_score = score
                    if best is not None:
                        prev = self.model.wall_damage_edge[self.model._edge(self.pos, best)]
                        if self.model.damage_wall_edge(self.pos, best, inc=1):
                            self.ap -= 2
                            self.log.append(f"Brecha pared hacia {best} (daño {prev}-> {self.model.wall_damage_edge[self.model._edge(self.pos, best)]}). AP={self.ap}")
                            continue

            # Nada funcionó: termina turno
            self.log.append("No pudo avanzar y no hay movimientos posibles. Termina turno.")
            self.ap = 0
            break

        if guard == 0:
            self.log.append("Guard de seguridad agotado. Termina turno por prevención.")
            self.ap = 0

        # Si no pudo moverse ni interactuar, intenta limpiar humo o apagar fuego en su celda
        if self.pos in self.model.smoke_positions and self.ap >= 1:
            self.clear_smoke(self.pos)
            self.log.append(f"Limpia humo en su celda {self.pos}. AP={self.ap}")
            return
        if self.pos in self.model.fire_positions and self.ap >= 2:
            self.extinguish_fire(self.pos)
            self.log.append(f"Apaga fuego en su celda {self.pos}. AP={self.ap}")
            return

    def _step_random(self):
        self.ap = self.max_ap
        self.log = [f"Astronauta {self.unique_id} (random) inicia turno en {self.pos} con {self.ap} AP."]
        self._interact_here()

        rng = getattr(self.model, "random", None)
        rand = (rng.random if rng else random.random)

        guard = 50
        while self.ap > 0 and guard > 0:
            guard -= 1

            # 30%: acción de seguridad adyacente (apagar/limpiar)
            if rand() < 0.30 and self._do_safety_adjacent():
                self.log.append("Random: acción de seguridad adyacente.")
                continue

            # Si carga: 60% de moverse 'dirigido' hacia el punto de entrega
            prefer = None
            if self.carrying:
                tgt = self.model.nursing_pos if self.carrying_status == 'alive' else self.model.airlock_pos
                if rand() < 0.60:
                    prefer = tgt

            old = self.pos
            if self._random_move(prefer_towards=prefer):
                if self.pos != old:
                    self.log.append(f"Random: se mueve {old} -> {self.pos}. AP={self.ap}")
                self._interact_here()
                continue

            # Si no pudo moverse, limpiar/apagar en su celda
            acted = False
            if self.pos in self.model.smoke_positions and self.ap >= 1:
                self.clear_smoke(self.pos)
                self.log.append(f"Random: limpia humo en {self.pos}. AP={self.ap}")
                acted = True
            elif self.pos in self.model.fire_positions and self.ap >= 2:
                self.extinguish_fire(self.pos)
                self.log.append(f"Random: apaga fuego en {self.pos}. AP={self.ap}")
                acted = True
            if acted:
                continue
            # 20%: intentar brecha aleatoria (si hay pared y alcanza AP)
            if rand() < 0.20 and hasattr(self.model, "damage_wall_edge") and self.ap >= 2:
                neigh = list(self.model.neighbors4(self.pos))
                if rng: rng.shuffle(neigh)
                else: random.shuffle(neigh)
                for nb in neigh:
                    e = self.model._edge(self.pos, nb)
                    if e in self.model.wall_damage_edge and self.model.wall_damage_edge[e] < 2:
                        prev = self.model.wall_damage_edge.get(e, 0)
                        if self.model.damage_wall_edge(self.pos, nb, inc=1):
                            self.ap -= 2
                            newd = self.model.wall_damage_edge.get(e, 0)
                            self.log.append(f"Random: brecha pared hacia {nb} (daño {prev}->{newd}). AP={self.ap}")
                            break
                else:
                    # No rompió nada
                    pass
                continue

            # Nada útil
            self.log.append("Random: sin acciones útiles. Termina turno.")
            self.ap = 0
            break

        if guard == 0:
            self.log.append("Random: guard agotado. Termina turno por prevención.")
            self.ap = 0


    def step(self):
        """Ejecuta la estrategia seleccionada: 'reasoned' o 'random'."""
        if self.strategy == "random":
            return self._step_random()
        # Default
        return self.step_reasoned()


    def knockdown(self):
        """
        Derribo por explosión:
        - Si estaba cargando, suelta y la víctima muere en su celda.
        - Reubica al astronauta en una celda LIBRE del perímetro (o la primera libre que encuentre).
        - Termina su turno.
        """
        # Si cargaba, suelta y muere
        if self.carrying and self.carrying_status in ("alive", "dead"):
            # Añade/actualiza POI muerto en la celda actual
            if isinstance(self.model.poi_positions, list):
                if self.pos not in self.model.poi_positions:
                    self.model.poi_positions.append(self.pos)
            else:
                self.model.poi_positions.add(self.pos)
            self.model.victim_status[self.pos] = "dead"
            self.carrying = False
            self.carrying_status = None
            self.log.append(f"Derribado: suelta víctima que muere en {self.pos}.")

        # Buscar perímetro libre
        perimeter = self.model._free_perimeter_spawns()
        empty_perimeter = [p for p in perimeter if self.model.grid.is_cell_empty(p)]

        new_pos = None
        if empty_perimeter:
            # Usa self.model.random si la tienes configurada; si no, random global
            rng = getattr(self.model, "random", None)
            new_pos = (rng.choice(empty_perimeter) if rng else random.choice(empty_perimeter))
        else:
            # Fallback: primera celda libre que encontremos (interior o borde)
            for y in range(self.model.H):
                for x in range(self.model.W):
                    pos = (x, y)
                    if self.model.grid.is_cell_empty(pos):
                        new_pos = pos
                        break
                if new_pos is not None:
                    break

        if new_pos is not None:
            old_pos = self.pos
            self.model.grid.move_agent(self, new_pos)
            self.log.append(f"Derribado: movido de {old_pos} a perímetro/seguro {new_pos}.")
        else:
            self.log.append("Derribado: sin celda libre para reubicar (permanece en su lugar).")

        # Termina su turno
        self.ap = 0


    def step(self):
        self.log = [f"Astronauta {self.unique_id} inicia turno en {self.pos} con {self.max_ap} AP."]
        self.ap = self.max_ap
        self._interact_here()

        while self.ap > 0:
            if self.carrying:
                target = self.model.nursing_pos if self.carrying_status == 'alive' else self.model.airlock_pos

                if self._do_safety_adjacent():
                    self.log.append(f"Realiza acción de seguridad adyacente en {self.pos}.")
                    continue

                if self.pos == target:
                    if self.carrying_status == 'alive':
                        self.victims_saved += 1
                        self.log.append(f"Entrega víctima viva en {target}.")
                    else:
                        self.log.append(f"Entrega víctima muerta en {target}.")
                    self.carrying = False
                    self.carrying_status = None
                    continue

                if self._advance_towards(target):
                    self.log.append(f"Se mueve hacia {target}.")
                    self._interact_here()
                    continue

                old = self.pos
                if self._random_move():
                    self.log.append(f"Se mueve aleatoriamente: {old} -> {self.pos}.")
                    continue
                else:
                    self.log.append("Atorado: sin movimientos posibles. Termina su turno.")
                    self.ap = 0
                    break

                self.log.append(f"Se mueve aleatoriamente desde {self.pos}.")
                continue

            if self._do_safety_adjacent():
                self.log.append(f"Realiza acción de seguridad adyacente en {self.pos}.")
                continue

            prev_carry = self.carrying
            self._interact_here()
            if self.carrying and not prev_carry:
                self.log.append(f"Recoge víctima {self.carrying_status} en {self.pos}.")
                continue

            target = self._select_target()
            if target is None:
                old = self.pos
                if self._random_move():
                    self.log.append(f"Se mueve aleatoriamente: {old} -> {self.pos}.")
                    continue
                else:
                    self.log.append("Atorado: sin movimientos posibles. Termina su turno.")
                    self.ap = 0
                    break
                self.log.append(f"No hay objetivo. Se mueve aleatoriamente desde {self.pos}.")
                continue

            if self._advance_towards(target):
                self.log.append(f"Se mueve hacia objetivo en {target}.")
                self._interact_here()
                continue

            old = self.pos
            if self._random_move():
                    self.log.append(f"Se mueve aleatoriamente: {old} -> {self.pos}.")
                    continue
            else:
                    self.log.append("Atorado: sin movimientos posibles. Termina su turno.")
                    self.ap = 0
                    break
            self.log.append(f"No pudo avanzar. Se mueve aleatoriamente desde {self.pos}.")

    def _dist(self, a, b):
        return abs(a[0]-b[0]) + abs(a[1]-b[1])

    def _open_adjacent_door_towards(self, target):
        """
        Abre (1 AP) la PUERTA CERRADA en la dirección que más acerque al target.
        Útil cuando no pudimos movernos pero queremos preparar el avance del próximo paso.
        """
        if self.ap <= 0 or target is None:
            return False
        best = None
        best_d = 10**9
        for nb in self.model.neighbors4(self.pos):
            if self._edge_is_door_closed(self.pos, nb):
                d = self._dist(nb, target)
                if d < best_d:
                    best = nb; best_d = d
        if best is not None:
            return self.open_door_between(self.pos, best)
        return False

    def _sidestep_towards(self, target):
        """
        Intenta un paso 'lateral' (sin A*/BFS) hacia vecinos transitables y libres
        que reduzcan (o mantengan) la distancia Manhattan al target.
        """
        if target is None or self.ap <= 0:
            return False
        candidates = []
        best_d = 10**9
        for nb in self.model.neighbors4(self.pos):
            if nb in self.model.fire_positions:
                continue
            if not self.model.can_traverse(self.pos, nb):
                continue
            if not self._cell_free(nb):
                continue
            d = self._dist(nb, target)
            if d <= self._dist(self.pos, target):
                candidates.append((d, nb))
                best_d = min(best_d, d)
        # Priorizamos los que más acercan
        candidates = [nb for (d, nb) in sorted(candidates, key=lambda x: x[0])]
        for nb in candidates:
            if self._try_move(nb):
                self.log.append(f"Paso lateral hacia {target}: {nb}. AP={self.ap}")
                return True
        return False

    def _random_push_door(self):
        """
        En modo random (o fallback), intenta abrir cualquier puerta cerrada adyacente (1 AP).
        """
        if self.ap <= 0:
            return False
        neigh = list(self.model.neighbors4(self.pos))
        rng = getattr(self.model, "random", None)
        if rng: rng.shuffle(neigh)
        else: random.shuffle(neigh)
        for nb in neigh:
            if self._edge_is_door_closed(self.pos, nb):
                if self.open_door_between(self.pos, nb):
                    self.log.append(f"Random: abre puerta hacia {nb}. AP={self.ap}")
                    return True
        return False

# =========================
# Parser para mapa de 6x8
# =========================
def parse_map_6x8_file(path):
    """
    Formato:
      - 6 líneas con 8 grupos de 4 dígitos 'ULDR': 1=pared, 0=libre.
      - POIs: r c t  (t in {v|f})  -> victima|falsa
      - Fuego: r c   (múltiples líneas) hasta que aparezcan puertas
      - Puertas: r1 c1 r2 c2  (múltiples)
      - Entradas: r c  (múltiples al final)

    Devuelve: dict con W=8, H=6, walls=set(edges), doors=set(edges),
              pois=[((x,y), 'alive'|'none')], fires=set((x,y)), entries=[(x,y)]
    """
    with open(path, "r") as f:
        raw = [ln.strip() for ln in f if ln.strip()]

    H, W = 6, 8
    wall_lines = raw[:H]
    i = H

    def edge(a, b):
        return frozenset((a, b))

    # ---- PAREDES (internas) ----
    walls = set()
    for r in range(H):  # r: 0..5
        groups = wall_lines[r].split()
        if len(groups) != W:
            raise ValueError(f"Línea {r+1}: se esperaban {W} grupos, obtuve {len(groups)}.")
        for c in range(W):  # c: 0..7
            bits = groups[c]
            if len(bits) != 4 or any(ch not in "01" for ch in bits):
                raise ValueError(f"Grupo inválido en r={r+1}, c={c+1}: '{bits}'")
            U, L, D, R = (bits[0] == '1', bits[1] == '1', bits[2] == '1', bits[3] == '1')
            x, y = c, r
            # Sólo añadimos arista si el vecino está dentro del mapa
            if U and y-1 >= 0: walls.add(edge((x, y), (x, y-1)))
            if L and x-1 >= 0: walls.add(edge((x, y), (x-1, y)))
            if D and y+1 < H:  walls.add(edge((x, y), (x, y+1)))
            if R and x+1 < W:  walls.add(edge((x, y), (x+1, y)))

    # ---- POIs (r c t) t in {v,f} ----
    pois = []
    while i < len(raw):
        parts = raw[i].split()
        if len(parts) == 3 and parts[2].lower() in ("v", "f"):
            r, c, t = parts
            r, c = int(r), int(c)
            status = 'alive' if t.lower() == 'v' else 'none'
            pois.append(((c-1, r-1), status))
            i += 1
        else:
            break

    # ---- FUEGO (r c) hasta que aparezcan puertas (4 ints) ----
    fires = set()
    while i < len(raw):
        parts = raw[i].split()
        # si son 4 enteros -> puertas
        if len(parts) == 4 and all(p.replace('-', '').isdigit() for p in parts):
            break
        # si son 2 enteros -> fuego
        if len(parts) == 2 and all(p.replace('-', '').isdigit() for p in parts):
            r, c = map(int, parts)
            fires.add((c-1, r-1))
            i += 1
        else:
            # línea inesperada
            break

    # ---- PUERTAS (r1 c1 r2 c2) hasta que aparezcan entradas (2 ints) ----
    doors = set()
    while i < len(raw):
        parts = raw[i].split()
        if len(parts) == 4 and all(p.replace('-', '').isdigit() for p in parts):
            r1, c1, r2, c2 = map(int, parts)
            a = (c1-1, r1-1); b = (c2-1, r2-1)
            if abs(a[0]-b[0]) + abs(a[1]-b[1]) != 1:
                raise ValueError(f"Puerta no adyacente: {(r1,c1)}~{(r2,c2)}")
            doors.add(edge(a, b))
            i += 1
        else:
            break

    # ---- ENTRADAS (r c) resto del archivo ----
    entries = []
    while i < len(raw):
        parts = raw[i].split()
        if len(parts) == 2 and all(p.replace('-', '').isdigit() for p in parts):
            r, c = map(int, parts)
            entries.append((c-1, r-1))
            i += 1
        else:
            raise ValueError(f"Línea no reconocida al final: '{raw[i]}'")

    return dict(W=W, H=H, walls=walls, doors=doors, pois=pois, fires=fires, entries=entries)

# =========================
# SECCIÓN 4 — Modelo
# =========================

from mesa import Model
from mesa.space import MultiGrid
from mesa.time import RandomActivation
from mesa.datacollection import DataCollector
import random
import numpy as np

class SpaceFightersModel(Model):
    def __init__(self,
                 n_astronauts=6,
                 n_fire=6, n_smoke=1,
                 num_alive_pois=10, num_false_alarms=5, num_dead_pois=0,
                 max_ap=4, seed=None,
                 default_strategy="reasoned",
                 agent_strategies=None,
                 rescued_target=7,
                 lost_threshold=4,
                 damage_threshold=25,
                 initial_damage=24,
                 replenish_pois=False,
                 map_file=None):
        super().__init__()
        if seed is not None:
            random.seed(seed); np.random.seed(seed)
            self.random = random

        # --- Reglas/Estrategias/Estado base ---
        self.default_strategy  = default_strategy or "reasoned"
        self.agent_strategies  = list(agent_strategies) if agent_strategies is not None else None
        self.rescued_target    = rescued_target
        self.lost_threshold    = lost_threshold
        self.damage_threshold  = damage_threshold
        self.replenish_pois    = replenish_pois

        # Estructuras
        self.wall_damage_edge = {}
        self.door_state_edge  = {}
        self.poi_positions    = set()
        self.victim_status    = {}
        self.fire_positions   = set()
        self.smoke_positions  = set()

        self.max_ap = max_ap

        # Grid + scheduler
        if map_file:
            data = parse_map_6x8_file(map_file)
            self.W, self.H = data["W"], data["H"]  # (8,6)
            self.grid = MultiGrid(self.W, self.H, torus=False)
            self.schedule = RandomActivation(self)

            # Cargar paredes/puertas
            for e in data["walls"]:
                self.wall_damage_edge[e] = 0
            for e in data["doors"]:
                self.door_state_edge[e] = "closed"
                self.wall_damage_edge.pop(e, None)  # puerta prevalece

            # Posiciones especiales (ajústalas si quieres otra regla)
            self.nursing_pos = (0, 0)
            self.airlock_pos = (self.W-1, self.H-1)

            # Agentes desde entradas (usa self.max_ap ya disponible)
            self._place_astronauts_from_entries(data["entries"], n_astronauts)

            # Objetos
            for (pos, st) in data["pois"]:
                self.poi_positions.add(pos)
                self.victim_status[pos] = st
            self.fire_positions = set(data["fires"])

        else:
            # Ruta alternativa (p. ej., 9x8)
            self.W, self.H = 9, 8
            self.grid = MultiGrid(self.W, self.H, torus=False)
            self.schedule = RandomActivation(self)

            self.setup_edge_map_9x8()
            self._place_astronauts(n_astronauts)
            self._place_fire(n_fire)
            self._place_initial_smoke(n_smoke)
            self._place_pois_pool(num_alive=num_alive_pois,
                                  num_false=num_false_alarms,
                                  num_dead=num_dead_pois)

        # Estado temporal y daño inicial
        self.turn = 0
        self.current_step = 0
        self.damage_markers = max(0, min(int(initial_damage), self.damage_threshold))
        self.game_over = False
        self.status = "En curso"
        self.finished_at = None

        # DataCollector (como ya lo tienes)
        self.datacollector = DataCollector(
            model_reporters={
                "rescued": lambda m: sum(getattr(a, "victims_saved", 0) for a in m.schedule.agents),
                "lost":    lambda m: m.count_lost(),
                "damage_markers": lambda m: m.damage_markers,
                "turn":    lambda m: m.turn,
                "status":  lambda m: m.status,
            },
            agent_reporters={
                "Víctimas Rescatadas": lambda a: getattr(a, "victims_saved", 0),
                "Fuegos Apagados":     lambda a: getattr(a, "fires_extinguished", 0),
                "Humo Apagado":        lambda a: getattr(a, "smoke_cleared", 0),
                "POIs Descubiertos":   lambda a: getattr(a, "pois_found", 0),
            }
        )
        self.datacollector.collect(self)

    # ---------- ARISTAS ----------
    def _edge(self, a, b):
        return frozenset((a, b))

    def neighbors4(self, pos):
        x, y = pos
        for nx, ny in ((x+1,y),(x-1,y),(x,y+1),(x,y-1)):
            if 0 <= nx < self.W and 0 <= ny < self.H:
                yield (nx, ny)

    def edge_is_wall_solid(self, a, b):
        e = self._edge(a, b)
        dmg = self.wall_damage_edge.get(e, None)
        # Solo es pared si EXISTE esa arista en wall_damage_edge y su daño < 2
        return (dmg is not None) and (dmg < 2)

    def planning_passable(self, a, b):
        # En planificación, paredes sólidas bloquean; puertas cerradas se permiten
        return not self.edge_is_wall_solid(a, b)

    def can_traverse(self, a, b):
        # Para moverse/actuar: paredes sólidas y puertas cerradas bloquean
        if self.edge_is_wall_solid(a, b):
            return False
        if self.edge_is_door_closed(a, b):
            return False
        return True

    def edge_is_door_closed(self, a, b):
        e = self._edge(a, b)
        return self.door_state_edge.get(e) == "closed"

    # ---------- MAPA COMPACTO ----------


    # ---------- SPAWNS ----------
    def _perimeter_cells(self, exclude=None):
        """
        Devuelve todas las celdas del perímetro del grid en (x,y),
        excluyendo las coordenadas en 'exclude'.
        Por petición: excluye (0,0) y (W-1,H-1) => (8,7) en 9x8.
        """
        W = getattr(self, "W", self.grid.width)
        H = getattr(self, "H", self.grid.height)

        # Construye lista del perímetro (sin duplicar esquinas)
        perim = []
        # Fila superior (y=0)
        perim.extend([(x, 0) for x in range(W)])
        # Fila inferior (y=H-1)
        perim.extend([(x, H-1) for x in range(W)])
        # Columna izquierda (x=0), interior (sin esquinas)
        perim.extend([(0, y) for y in range(1, H-1)])
        # Columna derecha (x=W-1), interior (sin esquinas)
        perim.extend([(W-1, y) for y in range(1, H-1)])

        # Excluir duplicados manteniendo orden
        seen = set()
        perim_unique = []
        for p in perim:
            if p not in seen:
                seen.add(p)
                perim_unique.append(p)

        # Exclusiones
        excl = set(exclude or [])
        # Por tu requerimiento explícito:
        excl.add((0, 0))
        excl.add((W-1, H-1))  # (8,7) en 9x8

        # (Opcional) Evita zonas especiales si quedaran al borde
        if hasattr(self, "nursing_pos"):
            excl.add(self.nursing_pos)
        if hasattr(self, "airlock_pos"):
            excl.add(self.airlock_pos)

        # Devuelve perímetro sin excluidos
        return [p for p in perim_unique if p not in excl]

    def _free_perimeter_spawns(self):
        """
        Celdas del perímetro LIBRES para spawnear astronautas.
        Evita posiciones con fuego (y opcionalmente humo, si lo deseas).
        """
        perim = self._perimeter_cells()
        free = []
        for pos in perim:
            # La celda debe estar libre de agentes
            if not self.grid.is_cell_empty(pos):
                continue
            # Evita spawnear sobre fuego
            if pos in self.fire_positions:
                continue
            # (Opcional) Evita spawnear sobre humo
            # if pos in self.smoke_positions:
            #     continue
            free.append(pos)
        return free

    def _place_astronauts_from_entries(self, entry_positions, n, shuffle=True):
        """
        Coloca hasta n astronautas usando primero las entradas del archivo.
        Si faltan, completa con perímetro. Evita apilar cuando es posible.
        """
        rng = getattr(self, "random", None)

        # Preferimos entradas
        candidates = list(entry_positions)
        # Completa con perímetro si faltan lugares
        if len(candidates) < n:
            extras = [p for p in self._free_perimeter_spawns() if p not in candidates]
            if shuffle:
                if rng: rng.shuffle(extras)
                else:   random.shuffle(extras)
            candidates.extend(extras)

        if len(candidates) < n:
            raise RuntimeError(f"No hay suficientes celdas para {n} astronautas.")

        if shuffle:
            if rng: rng.shuffle(candidates)
            else:   random.shuffle(candidates)

        for i in range(n):
            pos = candidates[i]
            if not self.grid.is_cell_empty(pos):
                # busca vecino libre inmediato
                for nb in self.neighbors4(pos):
                    if self.grid.is_cell_empty(nb):
                        pos = nb; break

            strat = (self.agent_strategies[i] if isinstance(self.agent_strategies, (list, tuple))
                    and i < len(self.agent_strategies) else self.default_strategy)

            a = Astronaut(i, self, strategy=strat)
            # a.max_ap = self.max_ap  # innecesario: el Astronaut ya lee model.max_ap
            self.grid.place_agent(a, pos)
            self.schedule.add(a)

    # ---------- HELPERS DE COLOCACIÓN ----------
    def _is_buildable_floor(self, pos):
        """Se puede colocar fuego/humo/POI aquí (no exterior, no zonas especiales)."""
        x, y = pos
        # Usa self.W/self.H (o self.grid.width/height, ambos sirven si están sincronizados)
        W, H = self.W, self.H

        # Evitar perímetro/exterior
        if x in (0, W-1) or y in (0, H-1):
            return False

        # Evitar Nursing/Airlock
        if pos in (self.nursing_pos, self.airlock_pos):
            return False

        return True


    def _place_fire(self, n):
        rng = getattr(self, "random", None)
        attempts = 0
        while n > 0 and attempts < 10000:
            x = (rng.randint(1, self.W - 2) if rng else random.randint(1, self.W - 2))
            y = (rng.randint(1, self.H - 2) if rng else random.randint(1, self.H - 2))
            pos = (x, y)
            if self._is_buildable_floor(pos) and pos not in self.fire_positions:
                self.fire_positions.add(pos)   # <-- add, no append
                n -= 1
            attempts += 1

    def _place_initial_smoke(self, n):
        rng = getattr(self, "random", None)
        attempts = 0
        while n > 0 and attempts < 10000:
            x = (rng.randint(1, self.W - 2) if rng else random.randint(1, self.W - 2))
            y = (rng.randint(1, self.H - 2) if rng else random.randint(1, self.H - 2))
            pos = (x, y)
            if (self._is_buildable_floor(pos)
                and pos not in self.fire_positions
                and pos not in self.smoke_positions):
                self.smoke_positions.add(pos)  # <-- add
                n -= 1
            attempts += 1

    def _place_pois(self, n):
        rng = getattr(self, "random", None)
        attempts = 0
        while n > 0 and attempts < 10000:
            x = (rng.randint(1, self.W - 2) if rng else random.randint(1, self.W - 2))
            y = (rng.randint(1, self.H - 2) if rng else random.randint(1, self.H - 2))
            pos = (x, y)
            if self._is_buildable_floor(pos) and pos not in self.poi_positions:
                self.poi_positions.add(pos)  # <-- add
                # Tipos: 'alive', 'dead', 'none'
                choice = (rng.choice(["alive", "dead", "none"]) if rng else random.choice(["alive", "dead", "none"]))
                self.victim_status[pos] = choice
                n -= 1
            attempts += 1


    def count_lost(self):
        """Cuenta víctimas 'dead' (no cuenta falsas alarmas)."""
        return sum(1 for s in self.victim_status.values() if s == "dead")

    def _place_pois_pool(self, num_alive, num_false, num_dead=0):
        pool = (["alive"] * max(0, num_alive)
                + ["none"] * max(0, num_false)
                + ["dead"] * max(0, num_dead))
        rng = getattr(self, "random", None)
        if rng: rng.shuffle(pool)
        else: random.shuffle(pool)

        attempts = 0
        for status in pool:
            placed = False
            while not placed and attempts < 20000:
                x = (rng.randint(1, self.W - 2) if rng else random.randint(1, self.W - 2))
                y = (rng.randint(1, self.H - 2) if rng else random.randint(1, self.H - 2))
                pos = (x, y)
                attempts += 1
                if not self._is_buildable_floor(pos):
                    continue
                if pos in self.poi_positions or pos in self.fire_positions or pos in self.smoke_positions:
                    continue
                self.poi_positions.add(pos)     # <-- add
                self.victim_status[pos] = status
                placed = True

    # ---------- DINÁMICA DEL ENTORNO ----------
    def _explode(self, pos):
        """
        Explosión desde 'pos':
          - Paredes: suben daño; al cruzar a 2 (+1 marcador) quedan transitables.
          - Puertas: se abren, pero **NO** suman daño.
          - Si la arista ya es transitable, afecta al otro lado (knockdown/POI muere).
        """
        for nb in self.neighbors4(pos):
            e = self._edge(pos, nb)

            # Daño a pared (solo cuenta al cruzar de <2 a 2)
            if e in self.wall_damage_edge:
                prev = self.wall_damage_edge.get(e, 0)
                new = min(prev + 1, 2)
                self.wall_damage_edge[e] = new
                if prev < 2 and new == 2:
                    self.damage_markers += 1  # colapso de pared
            # Puerta: abrir sin dañar
            elif e in self.door_state_edge:
                if self.door_state_edge[e] != "open":
                    self.door_state_edge[e] = "open"  # <-- sin incrementar damage_markers

            # Efectos al otro lado si ya es transitable
            if self.can_traverse(pos, nb):
                for a in self.grid.get_cell_list_contents([nb]):
                    if isinstance(a, Astronaut):
                        a.knockdown()
                if nb in self.poi_positions:
                    self.victim_status[nb] = "dead"

    def _spread_fire(self):
        rng = getattr(self, "random", None)
        x = (rng.randint(1, self.W - 2) if rng else random.randint(1, self.W - 2))
        y = (rng.randint(1, self.H - 2) if rng else random.randint(1, self.H - 2))
        pos = (x, y)

        if pos in self.fire_positions:
            self._explode(pos)

        elif pos in self.smoke_positions:
            self.smoke_positions.discard(pos)  # <-- discard
            self.fire_positions.add(pos)       # <-- add

        else:
            if pos not in self.fire_positions:
                self.smoke_positions.add(pos)  # <-- add

    # ---------- CICLO ----------
    def step(self):
        if self.game_over:
            return

        # Agentes
        self.schedule.step()

        # (Opcional) ya NO reponemos POIs, salvo que explícitamente quieras:
        if self.replenish_pois and len(self.poi_positions) < 3:
            self._place_pois(3 - len(self.poi_positions))

        # Entorno
        self._spread_fire()

        # Avance y registro
        self.turn += 1
        self.current_step = self.turn
        self.datacollector.collect(self)

        # Condiciones de término
        rescued_total = sum(getattr(a, "victims_saved", 0) for a in self.schedule.agents)
        lost_total    = self.count_lost()

        if rescued_total >= self.rescued_target:
            self.game_over = True
            self.status = "Misión exitosa"
            self.finished_at = self.turn
            return

        if lost_total >= self.lost_threshold:
            self.game_over = True
            self.status = "Demasiadas víctimas perdidas"
            self.finished_at = self.turn
            return

        if self.damage_markers >= self.damage_threshold:
            self.game_over = True
            self.status = "Base colapsada"
            self.finished_at = self.turn
            return

# =========================
# SECCIÓN 5 — Parámetros, ejecución y reporte
# =========================
import time, datetime
import pandas as pd

# --- Parámetros de simulación ---
PARAMS = {
    "n_astronauts": 6,  # <<< 6 bomberos
    "n_fire": 6,
    "n_smoke": 1,
    "max_ap": 4,
    "seed": 42,
    "max_steps": 1000,
    # Pool de POIs
    "num_alive_pois": 10,
    "num_false_alarms": 5,
    "num_dead_pois": 0,
    # Reglas de fin
    "rescued_target": 7,
    "lost_threshold": 4,
    "damage_threshold": 25,
    "initial_damage": 24,
}

print("== Parámetros de la simulación ==")
for k, v in PARAMS.items():
    print(f"{k}: {v}")

# --- Instanciar y correr ---
start_time = time.time()
model = SpaceFightersModel(
    n_astronauts=PARAMS["n_astronauts"],
    n_fire=PARAMS["n_fire"], n_smoke=PARAMS["n_smoke"],
    max_ap=PARAMS["max_ap"], seed=PARAMS["seed"],
    # Reglas
    rescued_target=PARAMS["rescued_target"],
    lost_threshold=PARAMS["lost_threshold"],
    damage_threshold=PARAMS["damage_threshold"],
    initial_damage=PARAMS["initial_damage"],
    # Estrategia por defecto (puedes cambiar a "random")
    default_strategy="reasoned",
    replenish_pois=False,
    # <<< AQUÍ el archivo:
    map_file="mapa_6x8.txt",
)

#model.run_until_done(max_steps=PARAMS["max_steps"])

elapsed = str(datetime.timedelta(seconds=(time.time() - start_time)))
print("\n== Ejecución terminada ==")
print("Tiempo de ejecución:", elapsed)
steps_to_finish = model.finished_at if model.finished_at is not None else model.turn
print(f"Pasos requeridos para finalizar la simulación: {steps_to_finish}")
print(f"Estado final: {model.status}")

# --- Recolección de datos desde DataCollector ---
model_df  = model.datacollector.get_model_vars_dataframe()
agents_df = model.datacollector.get_agent_vars_dataframe()

# Métricas globales finales (con defensas por si faltan columnas)
if not model_df.empty:
    rescued = model_df["rescued"].iloc[-1] if "rescued" in model_df.columns else 0
    lost    = model_df["lost"].iloc[-1] if "lost" in model_df.columns else 0
    damage  = model_df["damage_markers"].iloc[-1] if "damage_markers" in model_df.columns else 0
else:
    rescued = lost = damage = 0

print("\n== Métricas globales (último estado) ==")
print(f"Víctimas salvadas: {rescued}")
print(f"Víctimas perdidas: {lost}")
print(f"Daño a la base: {damage}")

# --- Mostrar últimas filas de los DataFrames ---
print("\n== Últimos registros del modelo ==")
try:
    from IPython.display import display
    display(model_df.tail())
except Exception:
    print(model_df.tail())

print("\n== Últimos registros de los agentes ==")
try:
    from IPython.display import display
    display(agents_df.tail())
except Exception:
    print(agents_df.tail())

# --- Resumen por agente (último paso por AgentID) ---
print("\n== Resumen por Agente ==")
if agents_df is None or agents_df.empty:
    print("No hay datos de agentes (¿se ejecutaron 0 pasos?).")
else:
    tmp = (
        agents_df
        .reset_index()            # columnas: Step, AgentID, métricas...
        .sort_values("Step")
    )
    final_agent_data = tmp.groupby("AgentID", as_index=False).tail(1).set_index("AgentID")

    # Columnas esperadas (coinciden con agent_reporters de la Sección 4)
    columns_to_show = [
        "Víctimas Rescatadas",
        "Fuegos Apagados",
        "Humo Apagado",
        "POIs Descubiertos",
    ]
    # Filtra sólo las que existen realmente
    columns_to_show = [c for c in columns_to_show if c in final_agent_data.columns]

    if columns_to_show:
        try:
            from IPython.display import display
            display(final_agent_data[columns_to_show])
        except Exception:
            print(final_agent_data[columns_to_show])
        # Totales
        print("\n-- Verificación de Totales --")
        for col in columns_to_show:
            total = final_agent_data[col].sum()
            print(f"Total de {col.lower()} (suma de agentes): {total}")
    else:
        print("No hay métricas por agente disponibles. Revisa los nombres en agent_reporters.")

# --- (Opcional) Guardar CSVs ---
SAVE_CSV = False  # cambia a True si quieres guardar
if SAVE_CSV:
    model_df.to_csv("model_log.csv", index=True)
    agents_df.to_csv("agents_log.csv", index=True)
    print("\nSe guardaron 'model_log.csv' y 'agents_log.csv' en el directorio de trabajo.")

# =========================
# SECCIÓN 6 — Datos del DataCollector y visualizaciones rápidas
# =========================
import pandas as pd
import matplotlib.pyplot as plt

# Recuperar datos (por si se ejecuta esta celda de forma independiente)
model_df  = model.datacollector.get_model_vars_dataframe()
agents_df = model.datacollector.get_agent_vars_dataframe()

print("== Últimos registros del modelo ==")
try:
    from IPython.display import display
    display(model_df.tail())
except Exception:
    print(model_df.tail())

print("\n== Últimos registros de los agentes ==")
try:
    from IPython.display import display
    display(agents_df.tail())
except Exception:
    print(agents_df.tail())

# -----------------------------
# Limpieza y comprobaciones
# -----------------------------
if model_df is None or model_df.empty:
    print("\n[AVISO] model_df está vacío. ¿Se ejecutaron 0 pasos? Revisa run_until_done/max_steps.")
if agents_df is None or agents_df.empty:
    print("[AVISO] agents_df está vacío. ¿Se ejecutaron 0 pasos? Revisa run_until_done/max_steps.")

# =========================
# SECCIÓN 7 — Modelo de la animación (POIs vivos, muertos y falsas alarmas con color distinto)
# =========================

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib.colors import ListedColormap, BoundaryNorm
from matplotlib.collections import LineCollection

# Agregamos códigos para falsas alarmas y muertos
# (Si ya tenías POI_FALSE=10, conserva lo mismo y solo añade POI_DEAD=11)
EMPTY, SMOKE, FIRE, WALL, DOOR_CLOSED, DOOR_OPEN, POI_VICTIM, ASTRONAUT, NURSING_CODE, AIRLOCK_CODE, POI_FALSE, POI_DEAD = 0,1,2,3,4,5,6,7,8,9,10,11

# Paleta de colores
# - POI_VICTIM (viva)    -> morado  (#7E57C2)
# - POI_FALSE  (none)    -> lila    (#CE93D8)
# - POI_DEAD   (muerta)  -> naranja (#FB8C00)
colors = [
    '#FFFFFF',  # 0 vacío
    '#9E9E9E',  # 1 humo
    '#D32F2F',  # 2 fuego
    '#8B5A2B',  # 3 pared (no se usa en raster; paredes van como líneas)
    '#1B5E20',  # 4 puerta cerrada
    '#66BB6A',  # 5 puerta abierta (líneas discontinuas)
    '#7E57C2',  # 6 POI víctima viva (morado)
    '#FDD835',  # 7 astronauta (amarillo)
    '#1976D2',  # 8 nursing (azul)
    '#000000',  # 9 airlock (negro)
    '#CE93D8',  # 10 POI falsa alarma (lila)
    '#FB8C00',  # 11 POI muerta (naranja)
]
cmap = ListedColormap(colors)
# Sugerencia robusta: que norm se adapte automáticamente al tamaño de 'colors'
norm = BoundaryNorm(np.arange(-0.5, len(colors) - 0.5, 1), cmap.N)

def get_grid_for_animation(model):
    g = np.zeros((model.grid.height, model.grid.width), dtype=int)

    # 1) Lugares especiales primero (para no tapar astronautas después)
    nx, ny = model.nursing_pos; g[ny, nx] = NURSING_CODE
    axx, ayy = model.airlock_pos; g[ayy, axx] = AIRLOCK_CODE

    # 2) Estados de celda
    for (x, y) in model.smoke_positions: g[y, x] = SMOKE
    for (x, y) in model.fire_positions:  g[y, x] = FIRE

    # 3) POIs diferenciados por estado
    #    - 'alive' -> morado (POI_VICTIM)
    #    - 'dead'  -> naranja (POI_DEAD)
    #    - 'none'  -> lila   (POI_FALSE)
    for (x, y) in model.poi_positions:
        status = model.victim_status.get((x, y), 'none')
        if status == 'alive':
            g[y, x] = POI_VICTIM
        elif status == 'dead':
            g[y, x] = POI_DEAD
        else:
            g[y, x] = POI_FALSE

    # 4) Astronautas encima (para que se vean siempre)
    for a in model.schedule.agents:
        if getattr(a, "pos", None) is not None:
            x, y = a.pos
            g[y, x] = ASTRONAUT

    return g

def _edge_to_segment(a, b):
    (x1, y1), (x2, y2) = a, b
    if x1 != x2:  # segmento vertical
        x = min(x1, x2) + 0.5
        y0 = min(y1, y2) - 0.5
        y1_ = max(y1, y2) + 0.5
        return [(x, y0), (x, y1_)]
    else:         # segmento horizontal
        y = min(y1, y2) + 0.5
        x0 = min(x1, x2) - 0.5
        x1_ = max(x1, x2) + 0.5
        return [(x0, y), (x1_, y)]

def _compute_barrier_segments(model):
    walls_intact, walls_damaged, doors_closed, doors_open = [], [], [], []
    for e, dmg in model.wall_damage_edge.items():
        if dmg < 2:
            a, b = tuple(e)
            seg = _edge_to_segment(a, b)
            if dmg == 0:
                walls_intact.append(seg)
            else:
                walls_damaged.append(seg)
    for e, st in model.door_state_edge.items():
        a, b = tuple(e)
        seg = _edge_to_segment(a, b)
        if st == "closed":
            doors_closed.append(seg)
        else:
            doors_open.append(seg)
    return walls_intact, walls_damaged, doors_closed, doors_open

def animate_model(model, max_steps=200, interval=200, title_prefix=""):
    fig, ax = plt.subplots(figsize=(6,6))
    ax.set_xticks([]); ax.set_yticks([])

    # Rejilla
    ax.set_xticks(np.arange(-0.5, model.grid.width, 1), minor=True)
    ax.set_yticks(np.arange(-0.5, model.grid.height, 1), minor=True)
    ax.grid(which='minor', color='lightgray', linestyle='-', linewidth=0.5, alpha=0.4)

    im = ax.imshow(get_grid_for_animation(model), cmap=cmap, norm=norm, interpolation="nearest")
    title_text = ax.set_title(
        f"{title_prefix} | Turno {model.turn} | "
        f"Daño: {model.damage_markers}/{model.damage_threshold} "
        f"(restan {max(0, model.damage_threshold - model.damage_markers)}) | {model.status}"
    )

    wall0_lines = LineCollection([], colors='#8B5A2B', linewidths=2)
    wall1_lines = LineCollection([], colors='#EF6C00', linewidths=2)
    doorC_lines = LineCollection([], colors='#1B5E20', linewidths=2)
    doorO_lines = LineCollection([], colors='#66BB6A', linewidths=2, linestyles='dashed')
    ax.add_collection(wall0_lines)
    ax.add_collection(wall1_lines)
    ax.add_collection(doorC_lines)
    ax.add_collection(doorO_lines)

    def _upd(_i):
        if _i > 0 and not model.game_over:
            model.step()
        im.set_data(get_grid_for_animation(model))
        w0, w1, dc, do = _compute_barrier_segments(model)
        wall0_lines.set_segments(w0)
        wall1_lines.set_segments(w1)
        doorC_lines.set_segments(dc)
        doorO_lines.set_segments(do)
        title_text.set_text(
            f"{title_prefix} | Turno {model.turn} | "
            f"Daño: {model.damage_markers}/{model.damage_threshold} "
            f"(restan {max(0, model.damage_threshold - model.damage_markers)}) | {model.status}"
        )
        return (im, wall0_lines, wall1_lines, doorC_lines, doorO_lines, title_text)

    ani = animation.FuncAnimation(fig, _upd, frames=max_steps, interval=interval, blit=False)
    plt.tight_layout()
    return ani

# =========================
# SECCIÓN 8 — Animaciones dobles: reasoned vs random
# =========================
from IPython.display import display, HTML


base_kwargs = dict(
    n_astronauts=6, max_ap=4, seed=42,
    rescued_target=7, lost_threshold=4, damage_threshold=25,
    initial_damage=24, replenish_pois=False,
    map_file="mapa_6x8.txt"   # << usar el archivo del mapa
)


model_reasoned = SpaceFightersModel(**base_kwargs, default_strategy="reasoned")
model_random   = SpaceFightersModel(**base_kwargs, default_strategy="random")

anim_reasoned = animate_model(model_reasoned, max_steps=400, interval=200, title_prefix="Reasoned")
anim_random   = animate_model(model_random,   max_steps=400, interval=200, title_prefix="Random")

# Lado a lado (usa SOLO este método para no duplicar controles)
from IPython.display import display, HTML
html_r   = anim_reasoned.to_jshtml()
html_rnd = anim_random.to_jshtml()
display(HTML(f"""
<div style="display:flex;gap:16px;align-items:flex-start">
  <div style="flex:1;min-width:360px"><h3 style="margin:6px 0">Reasoned</h3>{html_r}</div>
  <div style="flex:1;min-width:360px"><h3 style="margin:6px 0">Random</h3>{html_rnd}</div>
</div>
"""))

# =========================
# SECCIÓN 9 — Resultados de ambas simulaciones
# =========================
import pandas as pd


def report_results(model, label=""):
    print(f"\n== Resultados finales — {label} ==")
    print(f"Turnos: {model.turn} | Estado: {model.status}")
    print(f"Daño total: {model.damage_markers} / {model.damage_threshold} "
          f"(restante: {max(0, model.damage_threshold - model.damage_markers)})")

    model_df  = model.datacollector.get_model_vars_dataframe()
    agents_df = model.datacollector.get_agent_vars_dataframe()
    if not model_df.empty:
        rescued = int(model_df["rescued"].iloc[-1]) if "rescued" in model_df.columns else 0
        lost    = int(model_df["lost"].iloc[-1]) if "lost" in model_df.columns else 0
        damage  = int(model_df["damage_markers"].iloc[-1]) if "damage_markers" in model_df.columns else 0
    else:
        rescued = lost = damage = 0

    print(f"Víctimas salvadas: {rescued} / {model.rescued_target}")
    print(f"Víctimas perdidas: {lost} / {model.lost_threshold}")


    print(f"Víctimas salvadas: {rescued}")
    print(f"Víctimas perdidas: {lost}")
    print(f"Daño a la base: {damage}")

    # Resumen por agente (último registro por AgentID)
    print("\n--- Resumen por Agente ---")
    if agents_df is None or agents_df.empty:
        print("No hay datos disponibles de agentes.")
    else:
        tmp = (agents_df.reset_index().sort_values('Step'))
        final_agent_data = tmp.groupby('AgentID', as_index=False).tail(1)
        # Columnas esperadas
        cols = ["Víctimas Rescatadas", "Fuegos Apagados", "Humo Apagado", "POIs Descubiertos"]
        cols = [c for c in cols if c in final_agent_data.columns]
        if cols:
            try:
                from IPython.display import display
                display(final_agent_data.set_index('AgentID')[cols])
            except Exception:
                print(final_agent_data.set_index('AgentID')[cols])
        else:
            print("No hay métricas por agente (verifica agent_reporters).")

    # Devuelve valores para comparar
    return dict(turn=model.turn, status=model.status, rescued=rescued, lost=lost, damage=damage)

# Reportes individuales
res_reasoned = report_results(model_reasoned, label="Reasoned")
res_random   = report_results(model_random,   label="Random")

# Resumen comparativo
summary = pd.DataFrame([
    {"Estrategia":"Reasoned", **res_reasoned},
    {"Estrategia":"Random",   **res_random},
])[["Estrategia","turn","status","rescued","lost","damage"]]

print("\n== Resumen comparativo ==")
try:
    from IPython.display import display
    display(summary)
except Exception:
    print(summary.to_string(index=False))